const priorities = {
  urgent: [
    "urgent",
    "urgence",
    "rapidement",
    "vite",
    "au plus vite",
    "immédiatement",
    "immediatement",
    "asap",
    "avant ce soir",
    "avant demain",
    "dernier délai",
    "dernier delai",
    "deadline",
    "échéance",
    "echeance",
    "retard",
    "en retard",
    "impayé",
    "impaye",
    "bloqué",
    "bloque",
    "compte piraté",
    "compte pirate",
    "passeport expiré",
    "passeport expire",
    "fuite d'eau",
    "enfant malade",
    "problème urgent",
    "probleme urgent",
  ],

  important: [
    "santé",
    "sante",
    "médecin",
    "medecin",
    "dentiste",
    "pédiatre",
    "pediatre",
    "enfant",
    "école",
    "ecole",
    "crèche",
    "creche",
    "administratif",
    "banque",
    "impôts",
    "impots",
    "caf",
    "cpam",
    "assurance",
    "mutuelle",
    "visa",
    "passeport",
    "facture",
    "edf",
    "loyer",
    "comptable",
    "urssaf",
    "inpi",
    "kbis",
    "contrat",
    "document officiel",
  ],

  flexible: [
    "plus tard",
    "quand j'aurai le temps",
    "quand jai le temps",
    "un jour",
    "éventuellement",
    "eventuellement",
    "si possible",
    "pas pressé",
    "pas presse",
  ],

  labels: {
    urgent: "Urgente",
    important: "Importante",
    normal: "Normale",
    flexible: "Flexible",
  },

  autoImportantCategories: [
    "Santé",
    "Enfant",
    "Administratif",
    "Finance",
    "Travail",
    "Voyage",
  ],
};

module.exports = priorities;
