// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4jTzqrn_G_9aF6n7-LOE8DNGPaGr2os',
    appId: '1:664245687438:web:47a6c5b48cd5c42dca65df',
    messagingSenderId: '664245687438',
    projectId: 'zelia-ai-app',
    authDomain: 'zelia-ai-app.firebaseapp.com',
    storageBucket: 'zelia-ai-app.firebasestorage.app',
    measurementId: 'G-BMG31SYTE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2TXp_o-ijZiw5zObZTk54kO4NVOHnATI',
    appId: '1:664245687438:android:176b756db5b132c6ca65df',
    messagingSenderId: '664245687438',
    projectId: 'zelia-ai-app',
    storageBucket: 'zelia-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmT0K90q5SyOH-xNiRYkznioEnjxyT5p4',
    appId: '1:664245687438:ios:448842c47ca8b283ca65df',
    messagingSenderId: '664245687438',
    projectId: 'zelia-ai-app',
    storageBucket: 'zelia-ai-app.firebasestorage.app',
    iosBundleId: 'com.sophiadfamily.zeliaaiapp',
  );
}
